### ISSUE TITLE
想请教一下如何运行

### ISSUE THREAD

**Issue by lvzhishang** [kahotv/QQTools#2]
之前没有接触过C#，在bin文件夹下也没有看见相关的exe文件，想问下该如何运行老哥您的代码呢？或者该使用哪款编译器运行后才会生成该文件？

**Comment by lvzhishang** [comment]
![image](https://user-images.githubusercontent.com/27761823/68821298-ea28f500-06c8-11ea-92b8-30d7e6b8a1ed.png)

不知道您能不能看见我的运行界面。。。

**Comment by lvzhishang** [comment]
> 之前没有接触过C#，在bin文件夹下也没有看见相关的exe文件，想问下该如何运行老哥您的代码呢？或者该使用哪款编译器运行后才会生成该文件？

我也是dnf的爱好者，也想试试该宝贝，哈哈哈

**Comment by kahotv** [comment]
很多活动已经下架了，也没有根据新活动继续维护，所以这个项目实用性很小。只有道聚城签到还能用。去下载发布版吧
